### PR TITLE
Ifm fixes and 100k

### LINKED ISSUE #93: ifm may delete applications on camera
**Current situation**
When constructed with `applicationId == -1` -- which is also the default -- the O3D3xx wrapper will erase all applications on the camera and install a default one during `Connect`.

**Desired behaviour**
* The O3D3xx wrapper should under no circumstances automatically erase applications on the camera
* Add a method `InstallDefaultApplication` or similar

### PR DESCRIPTION
**Pull request by jangernert**
- add and update 100k mode
- don't delete application on disconnect if it wasn't created on connect
- leave edit mode in case of exception during connect
- fixes #93

### CODE REVIEW

**Comment by jangernert** [comment]
@stephenmartindale 
```
IAsyncResult res = socket.BeginReceive(buffer, offset + received, size - received, SocketFlags.None, null, null);

CancellationToken token = _cancelUpdateThreadSource.Token;
token.Register(() =>
{
    socket.EndReceive(res);
    return;
});

res.AsyncWaitHandle.WaitOne();
received += socket.EndReceive(res);
```
Receiving the first image works fine, but as soon as I switch to 100k mode the received header still suggests a frame size of ~255k instead of the expected ~1m.
Anything I missed?

**Comment by stephenmartindale** [comment]
I did some reading about `System.Net.Sockets.Socket` and it seems that the *proper* way to cancel a pending receive is actually to close the socket. Some say that calling `EndReceive()` works, too, but may throw exceptions that need to be caught and ignored. Personally, I wouldn't want to try this without extensive testing and, since `_clientSocket` is going to be disconnected/closed immediately after the cancellation token is triggered, we don't really need it.

Some changes are still needed, however:

1. `Close()` the `_clientSocket` in `DisconnectImpl()` and make a new one when `ConnectImpl()` needs it.
2. Don't join the `_updateThread` until after the `_clientSocket` is closed, otherwise, you might deadlock on a pending receive that never returns.
3. In the `_updateThread`, handle the exception that `Receive()` throws if the socket is closed before / during the call to `Receive()` and end the thread. (This is to prevent the Framework treating that exception as unhandled)

File: BetaCameras/ifm/O3D3xx.cs [hunk 1]
```diff
@@ -326,6 +378,7 @@ protected override void ConnectImpl()
             string protocolVersion = _device.GetParameter("PcicProtocolVersion");
             if (_applicationId == -1)
             {
+                _cleanUpApplication = true;
                 for (int i = 1; i < 33; i++)
```
Comment (stephenmartindale) [inline BetaCameras/ifm/O3D3xx.cs]: Can you change this so that a new application is created if `_applicationId` is -1 and remove this loop that deletes all existing applications? (If too many existing applications already exist, throw an exception but do nothing. Basically, the camera object should *never* delete an application that it did not create and should always delete an application that it did create.

File: BetaCameras/ifm/O3D3xx.cs [hunk 2]
```diff
@@ -383,19 +433,26 @@ private void UpdateLoop()
...
+                        }
+                        Receive(_clientSocket, _backBuffer, 0, frameSize, 300000);
+                        _frameAvailable.Set();
                     }
-                    Receive(_clientSocket, _backBuffer, 0, frameSize, 300000);
-                    _frameAvailable.Set();
+                }
+                catch(SocketException e)
+                {
+                    log.Error($"{Name}: Socket Exception: {e.Message}");
```
Comment (stephenmartindale) [inline BetaCameras/ifm/O3D3xx.cs]: Just logging the exceptions isn't enough. The thread should also end at some point (perhaps after 3 consecutive socket exceptions?) or else you'll end up with a tight-loop that's just filling up the log with errors. If the thread does "crash" in this way, the camera object should raise an event or at least expose a flag indicating that the connection has failed. It might be a good idea to leave the object in a failed, but clean, state so that a call to `Connect()` will be able to attempt a reconnect with a new socket and a new worker thread.

File: BetaCameras/ifm/O3D3xx.cs [hunk 3]
```diff
@@ -32,6 +32,56 @@ private enum Mode
...
+                // reset frame available to force a new frame with the correct resolution 
+                _frameAvailable.Reset();
+            }
+        }
+        private ParamDesc<bool> Resolution100kDesc
+        {
+            get
+            {
+                ParamDesc<bool> res = new ParamDesc<bool>();
+                res.Description = "100k px resolution";
```
Comment (stephenmartindale) [inline BetaCameras/ifm/O3D3xx.cs]: Can you include the width and height of the images in this string?

File: BetaCameras/ifm/O3D3xx.cs [hunk 4]
```diff
@@ -381,22 +432,43 @@ protected override void ConnectImpl()
...
                 {
-                    if (_backBuffer.Length != frameSize)
+                    consecutiveFailCounter++;
+                    log.Error($"{Name}: Socket Exception: {e.Message}");
+
+                    if(consecutiveFailCounter >= _maxConsecutiveReceiveFails)
                     {
-                        _backBuffer = new byte[frameSize];
+                        log.Error($"{Name}: Receive failt more than {_maxConsecutiveReceiveFails} times in a row. Shutting down update loop.");
+                        DisconnectImpl();
```
Comment (stephenmartindale) [inline BetaCameras/ifm/O3D3xx.cs]: This will result in a deadlock. The MSDN says: "*You should never call the Join method of the Thread object that represents the current thread from the current thread. This causes your app to hang because the current thread waits upon itself indefinitely,*"

File: BetaCameras/ifm/O3D3xx.cs [hunk 5]
```diff
@@ -381,22 +432,43 @@ protected override void ConnectImpl()
...
+                catch(SocketException e)
                 {
-                    if (_backBuffer.Length != frameSize)
+                    consecutiveFailCounter++;
+                    log.Error($"{Name}: Socket Exception: {e.Message}");
+
+                    if(consecutiveFailCounter >= _maxConsecutiveReceiveFails)
                     {
-                        _backBuffer = new byte[frameSize];
+                        log.Error($"{Name}: Receive failt more than {_maxConsecutiveReceiveFails} times in a row. Shutting down update loop.");
```
Comment (stephenmartindale) [inline BetaCameras/ifm/O3D3xx.cs]: * "failed"

Perhaps: `$"{Name}: Receive failed {consecutiveFailCounter} times in a row. Shutting down update loop."`

**Comment by jangernert** [comment]
@stephenmartindale I was in the process of testing what you described earlier. But somehow I got the camera to act up. No image is shown even in the ifm application. I'll continue with this on Wednesday.
